import { test, expect } from '@playwright/test';

test('durable tape import, native cohorts, lineage, repricing and publication',async({page,request})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  const settings=await(await request.get('/api/settings')).json();
  expect((await request.put('/api/settings',{data:{...settings,n_paths:32,n_paths_base:32,n_threads:2,horizon_months:3,compute_backend:'rust'}})).ok()).toBeTruthy();
  await page.goto('/');
  await page.getByRole('button',{name:'Open Tape & Cohorts',exact:true}).click();
  const panel=page.getByRole('region',{name:'Tape & Cohorts',exact:true});
  await expect(panel.getByLabel('Cohort rules JSON')).toContainText('credit_card');
  await panel.getByRole('button',{name:'Load synthetic example',exact:true}).click();
  await expect(panel.getByText('Immutable tape saved. Review the rules, then build cohorts.')).toBeVisible({timeout:30000});
  await panel.getByRole('button',{name:'Build cohorts',exact:true}).click();
  await expect(panel.getByText(/20 loans → 5 cohorts/)).toBeVisible({timeout:30000});
  await panel.getByRole('button',{name:'Pin as comparison baseline',exact:true}).click();
  const rules=JSON.parse(await panel.getByLabel('Cohort rules JSON').inputValue());
  await panel.getByLabel('mortgage fico bucket edges').fill('746, 747');
  await panel.getByLabel('mortgage fico bucket edges').press('Tab');
  await panel.getByRole('button',{name:'Build cohorts',exact:true}).click();
  await expect(panel.getByText(/Changed cohort identities: 4 loans/)).toBeVisible({timeout:30000});
  await panel.getByLabel('Loan ID',{exact:true}).fill('mortgage-000');
  await panel.getByRole('button',{name:'Find cohort',exact:true}).click();
  await expect(panel.getByRole('cell',{name:'mortgage-000',exact:true})).toBeVisible();
  await panel.getByRole('button',{name:'Price cohorts',exact:true}).click();
  await expect(panel.getByText(/Representative cohort repricing — weighted terms/)).toBeVisible({timeout:30000});
  await panel.getByRole('button',{name:'Reprice original loan',exact:true}).click();
  await expect(panel.getByText(/Individual model repricing — original loan terms/)).toBeVisible({timeout:30000});
  await panel.getByRole('button',{name:'Allocate cohort cashflows to loans',exact:true}).click();
  await expect(panel.getByText(/Balance-weighted allocation — not individual repricing/)).toBeVisible({timeout:30000});
  await panel.getByRole('button',{name:'Audit all selected loans',exact:true}).click();
  await expect(panel.getByText(/Accuracy audit:/)).toBeVisible({timeout:30000});
  await panel.getByRole('button',{name:'loan risk',exact:true}).click();
  await expect(panel.getByText(/First 100 rows shown. Full partitioned outputs:/)).toBeVisible();
  await panel.getByRole('button',{name:'Replace selected books with cohorts',exact:true}).click();
  await expect(panel.getByText(/Published (mbs, deposits|deposits, mbs) at revision/)).toBeVisible({timeout:30000});
  const books=await(await request.get('/api/books')).json();
  expect(books.mbs.positions).toBe(3);expect(books.deposits.positions).toBe(1);
  const count=Object.values(books).reduce((n:number,b:unknown)=>n+(b as {positions:number}).positions,0);
  await expect(page.getByRole('region',{name:'Positions',exact:true}).getByText(`${count} positions`,{exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/cohorts-real.png',fullPage:true});
  expect(errors).toEqual([]);
  expect(await page.locator('vite-error-overlay').count()).toBe(0);
});
